### ISSUE TITLE
Installation av==8.1.0

### ISSUE THREAD

**Issue by maximelianos** [robot-learning-freiburg/PointFlowMatch#1]
While running `bash bash/install_deps.sh` the package `av==8.1.0` failed to install with
```
ModuleNotFoundError: No module named 'distutils.msvccompiler'
```

This package is required by the project's `pyproject.toml`

My OS is Ubuntu 22.04, using miniconda as recommended in instructions.

**Comment by chisarie** [comment]
Hi, from our discussion I understand this is resolved

**Comment by Trav1slaflame** [comment]
Dear teams,

I also meet this issue, may I ask what is the solution for it?

Thanks

**Comment by maximelianos** [comment]
For me it worked by requiring any later version:  "av>=8.1.0"

**Comment by Trav1slaflame** [comment]
> For me it worked by requiring any later version: "av>=8.1.0"

Hi teams,

I already solved this issue by downgrading the setuptools to version 64. thanks for your time.
